version: '3.1'

services:
  msgbroker:
    image: rabbitmq:3-management-alpine
    container_name: ctn_msgbrokr
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    networks:
      - dev-network
    healthcheck:
      test: "exit 0"
  srvapi:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SRC=${SRCDIR}
        - LOG=${LOGDIR}
        - RUN=${RUNDIR}
        - ETC=${ETCDIR}
        - BIN=${BINDIR}
        - APPNAME=${APPNAME}
    ports:
      - 8080:8080
    volumes:
      - ${LOGDIR}:${LOGDIR}
    depends_on:
      msgbroker:
        condition: service_healthy
    networks:
      - dev-network
    environment: 
      - LOGF=${LOGDIR}/botmincock.log
      - GIN_MODE=${GIN_MODE}
    stdin_open: ${TTYSTDIN} 
    tty: ${TTYSTDIN}
    container_name: ctn_srvapi
    entrypoint: ["${BINDIR}/entry.sh", "-v ${VERBOSE}", "-f ${FLOG}"]
    secrets:
      - my_secret
secrets:
  my_secret:
    file: sample.secret
networks:
  dev-network:
    driver: bridge